displayName: "DynamicHost"
type: "middleware"

import: "github.com/slimani-dev/dynamichost"

summary: "DynamicHost Plugin for Traefik"

testData:
  Headers:
    - name: "Host"
      regexPattern: "^(.*)\\.localhost$"
      newHost: "$1.example.com"
