displayName: DynamicHost
type: middleware

import: github.com/slimani-dev/dynamic-host

summary: '[Demo] Add Request Header'

testData:
  Headers:
    - Header
      name: Host 
      regexPattern: "^([^.]+)\\.localhost$"
      newHost: "$1.example.com"